[workspace]
members = [
    "crates/rml-contracts",
    "crates/rml-proc",
    "crates/rml-proc-dummy",
    "crates/rml-syn",
    "crates/example",
    "crates/cargo-rml",
    "crates/rml",
]
resolver = "2"
default-members = ["crates/example"]

[profile.release]
lto = true
