[package]
name = "rml"
authors = ["Daniel Drodt <daniel.drodt@tu-darmstadt.de>"]
version = "0.1.0"
edition = "2024"

[dependencies]
rml-syn = { path = "../rml-syn" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"

[package.metadata.rust-analyzer]
rustc_private = true
